### ISSUE TITLE
Don't follow this

### ISSUE THREAD

**Issue by prakharmehta95** [prakharmehta95/commsolar#13]
https://github.com/prakharmehta95/commsolar/blob/114257609d526d3daea31abf76a2a4866de220cc/code/COSA_Agent/BuildingAgent.py#L1227

I don't know how this works hence confused - and just wondering if this leads to the right prices at the right times. Have you checked this?

**Comment by anunezji** [comment]
This is just a numerical trick to simplify the use of time-of-use electricity tariffs. ratio_high_low indicates the ratio between high and low electricity prices during hours with high and low prices. el_p_ind is the reference electricity price used to compute the prices at high and low price hours. The weird fractions in there stem from the computation of the average weighted electricity price considering how many hours of high and low prices there are in one week. So that: el_p_ind = a*el_p_l + b*el_p_h.

I believe there are more details in the excel for electricity prices
