### ISSUE TITLE
v instead of ix?

### ISSUE THREAD

**Issue by prakharmehta95** [prakharmehta95/commsolar#4]
https://github.com/prakharmehta95/commsolar/blob/2224f68a548c32cd68189acc8b202ca1c39fc355/code/COSA_Tools/npv_ind.py#L435

I think it should be:
pvp_ix = next(**v** for ix, v in enumerate(pv_categs) if v > pv_cap[_i])

Because the pv sizes are actually in the value and not key, and later when it is referenced to the input dictionary it will take the price based on the size (and not just the index which may be an incorrect reference?)

Or may be I misunderstood this.

**Comment by anunezji** [comment]
No, the code is correct because what we need here is the index that tells us what item in the list is bigger than the size of PV we have. With the index ix we can then go and pick the price that is in the prior position in the list ix - 1.

IMPORTANT: I am moving away from this code and using an empirical relation between size and scale effects from a survey in Switzerland from the most recent IEA PVPS report. I will commit the changes later tonight
