### ISSUE TITLE
lifetime_cashflows has an extra year

### ISSUE THREAD

**Issue by prakharmehta95** [prakharmehta95/commsolar#7]
https://github.com/prakharmehta95/commsolar/blob/114257609d526d3daea31abf76a2a4866de220cc/code/COSA_Agent/BuildingAgent.py#L1384

when this repitition is done: `lifetime_cashflows = lifetime_cashflows.append([cf_y] * PV_lifetime, ignore_index=True)`
the resulting df `lifetime_cashflows` has 26 instead of 25 years of cashflows. 

Suggestion: `lifetime_cashflows = lifetime_cashflows.append([cf_y] * (PV_lifetime-1), ignore_index=True)`

Not a huge error, and had to be same for all results we have had so far - so it doesn't help explain the grid costs issue we face

**Comment by anunezji** [comment]
Thanks for spotting this.

This is now solved for both community cash flow calculations (sys == "com") and individual installations (sys == "ind").

Individual systems is fixed with https://github.com/prakharmehta95/commsolar/commit/a1c29d0e97401929162b942f627157701142f86c 

Community systems is fixed with
https://github.com/prakharmehta95/commsolar/commit/74e0bf4a809010638397f9048054c44a80f3b9a2#
